language: java

sudo: false

jdk:
  - openjdk11

cache:
  directories:
    - ${HOME}/.m2
    - ${TRAVIS_BUILD_DIR}/native/tools/rpi-tools
    - ${TRAVIS_BUILD_DIR}/native/tools/osxcross

env:
  global:
    - secure: "cyGi5uKzodeHrbqtIpDDgtKC6a1uqxN5rCOVAqe34xuuFY0vQzzpa+zAo9HADbI7syCbcwrF33iE+y7CzNWSieEU7NY5GJNzXArSHedxZa9ywYIo01H/7Tjza6y6LyTEem6xLopUBQFBpGEty/92nj0YesUsDRgSiyTmAgUgRp3bvOm6WLSmtiDys6LBDhhUBjwOG7guhRMGraxg50ReVqCgo2B4zCBZ3LvOBMplDw49aNP+/QSK8y+hIBFfE1MGJHGUflac3XuWTO7PJnVPOwKqJ/EC/ONRDZW+m143PLxbwbkvlHFBltZOgg7Wo6EsfNDWp4h1yndEaeVSKE83uXLKDkDiITqHn07zmig//qOn1EDyhttQDGve5zamDSuyGIjzCXKxTAnwIXH55CNeAqaKbFmtQe/AqpznpX5RFixe7arcSCHWIxcbESentRhUOFkXNPbUXzJ8+76+tTPFXbeHndliQhksr+T0EfgiMTWGEOOh3IVLhAD40qLXraKMKNWvWsmHYXrhinOXZijQisJyYhp+uTaMIHgQx84k9JmJqIxUC/R0W1YlQDlST0oV+OR9RmBgPCInv7JpFU7UeLSuEhGlyp+4SalwkHG5Ya6AziywSr1sL52RW7XOoPKPDovYO4FLuPy7v8CAnbUx6XuN6KE0JNVitpnV4pWWUIM="
    - secure: "sgFfZu/uXQbjDqFd4JP1DB3Vdcw/8sF6uCeL5kB3IwaJaEi1jmvfC40ziFGaUSF2klvDO4DP30ZWdSXru/XL8ZXL9HvyOOyYthu2gq2KdNJZOmWA+8o5rh9R+HnpyOIfowP/aDMGkSGKuGKaScRMunoQ1D7N/7/3OyRY5JJIy3JrhHQi1/32A2bthrFzU1LUybYsqcoonNwbmijuwbr1uHsg68eR/cKQDbg7G8gCMFHKCSQqD00SC4arZlmLUOymrythf8nszrAr0IV34Inj777VzRNKt6TBdZnww/vUSNjODYujlo149YCxu2HO3vMzpfQwwVt1qOQa2lGZQjC1BuPVJN7TBf0VQX9FZxfv5X1rlNShevsjNgYopyPVBs4/lxaxzVn5I1qSJ4arW4SaK/K1P14dDCTZbdZAi2EpaCHcMT3o7a5byl0Xw1KrFHKVWR9pynkkpTJP57TJlIZmgxcG9vWWtraaUQMyQ8cRXDz2OMj9KNj/ffiwJvrEm7iDqrQ5wSaxiVj0cHHpn1qzVJQD7YEqejhFBUVgf+KK9EmXuaNjGhgehGE6WWTuR2MA3QohXlw8s2d0+azYJD2qcjx2iq9TWVIbzumDtgZYPNgxnSAcFx2uM4rEyWeBzuGFxB8enpIjjtvLzQ2sJRqjb0F+MTLCExn0LSlmLs+x4TI="
    - secure: "q3lGyhVwwuzkeTC21Tuk22vdHUcjy6373S+6+BJ86dXoXhNKC4t9tG8D+xELO0JNjgyLH9tAVVH/j55zAgKQUnBw2SKYBuMPKnUF3K4RgL8tUmw7rByWJIdoKy+0h2vA4dmGcEhYdN36bG+kVuVrGW33drlLeYgUrwteyjT3svFdkFOQcVaFznHobDlN/+SKvlwF6o71hUUQtBKFAyzSO9DNMS2LvqO54CgyNPnG2pY19ZSbIus+3Xve0EkpOeGZwjLPFJvagigbHigCltQvrVxAgJEMDQffVWxdH07WrG5xlER/xVCf6B56bW1Irk1Wlkd/sW2a9kh0fgtkXtjj9pYZL8+oh4uc3KB1rc0iOSju8kHlJN0141TKiqvzUaWHpBrNtyhWmc80K7uKft2joVKyJZgvaa3hradp1T75JBaBKfubhE6kcdix0w5lNmI0zAr6Clo0Z+IauskZVweDFNEthOsDIrWhan4QhvynEc7w1a+FuSo3eBXsYfrqVmO+2QLRkCYnofK8UEhdPJCnYQqIHcMliG4t09qUMC2a9r5GQiXeqib1aDnRLq4qkbLylbyS0mTsWjcv9lgy7QovEHnX1ygM2RS4mYI9pwAqwDecrPZ/azA9BD9CYqR86zqsdL+BL2/GgMCBcP9PuBiWoJU5cWGVvB1GY4px7w0Fm/A="

notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/f7f122123bd58ebb34f5"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      addons:
        apt:
          packages:
            - mingw-w64
            - autoconf-archive
            - llvm-9
            - llvm-9-dev
            - clang-9
            - gcc-7
            - g++-7
            - gcc-multilib
            - g++-multilib
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      env: PATH="/usr/bin:/usr/local/bin:${PATH}"
    - os: osx
      osx_image: xcode9.4

before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo ln -s /usr/bin/clang-9 /usr/local/bin/clang; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo ln -s /usr/bin/clang++-9 /usr/local/bin/clang++; fi
  #- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc; fi
  #- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++; fi
  #- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then export CC=gcc-7; fi
  #- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then export CXX=g++-7; fi
  - scripts/before-install.sh
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo echo "JAVA_HOME=${JAVA_HOME}"; fi

install:
  - echo "Install"
  #- scripts/install.sh

script:
  - cd scripts && ./build-native.sh native-build-cc-osx-x86_32
  #- scripts/verify-builds.sh
  #- mvn test && mvn verify

before_deploy:
  - echo "Before deploy"
  # - cp scripts/settings.xml $HOME/.m2/settings.xml

after_success:
  - echo "After success"
  #- scripts/deploy.sh