language: java

sudo: false

jdk:
- oraclejdk8

cache:
  directories:
  - ${TRAVIS_BUILD_DIR}/native/src/main/cpp/tools

env:
  global:
  - secure: "cyGi5uKzodeHrbqtIpDDgtKC6a1uqxN5rCOVAqe34xuuFY0vQzzpa+zAo9HADbI7syCbcwrF33iE+y7CzNWSieEU7NY5GJNzXArSHedxZa9ywYIo01H/7Tjza6y6LyTEem6xLopUBQFBpGEty/92nj0YesUsDRgSiyTmAgUgRp3bvOm6WLSmtiDys6LBDhhUBjwOG7guhRMGraxg50ReVqCgo2B4zCBZ3LvOBMplDw49aNP+/QSK8y+hIBFfE1MGJHGUflac3XuWTO7PJnVPOwKqJ/EC/ONRDZW+m143PLxbwbkvlHFBltZOgg7Wo6EsfNDWp4h1yndEaeVSKE83uXLKDkDiITqHn07zmig//qOn1EDyhttQDGve5zamDSuyGIjzCXKxTAnwIXH55CNeAqaKbFmtQe/AqpznpX5RFixe7arcSCHWIxcbESentRhUOFkXNPbUXzJ8+76+tTPFXbeHndliQhksr+T0EfgiMTWGEOOh3IVLhAD40qLXraKMKNWvWsmHYXrhinOXZijQisJyYhp+uTaMIHgQx84k9JmJqIxUC/R0W1YlQDlST0oV+OR9RmBgPCInv7JpFU7UeLSuEhGlyp+4SalwkHG5Ya6AziywSr1sL52RW7XOoPKPDovYO4FLuPy7v8CAnbUx6XuN6KE0JNVitpnV4pWWUIM="
  - secure: "oYXKZH9AnSc2Y5geyZe5fBVCsjUwrWivWw6XYcq5nnuatSDNPrewjVPcB4m2FiZMrwEJOwEAo41X1dPhtzQ35NLU8YIXqmjiGCbcre4vKpfHONFwoNNXfH5nPras+l3RR2W0Q1XnoySLiKydNJbVq5inpwX5HHV74/5+oOIzQzNjuDHVaw29uJ1Ud9B/hU73WuJHjjycGocEnU4ZatJMQG6ZoqCPcgH+9bVlETz/tNzaIisrTyfo2VMA5AhpmFTyMA2lOcbUsbZqOLoSVLr52LaTDbrCUbeNZYG8ADFg6K90/jt/iDkDHx4PxP2bIViM0YdcOehztNd9uFp1HmnHPc5fB7RjnVZncNMD83SPwzy2Kgc7qHGEX1lpdB4j29xYXQxR8xPeRv9GiBNXOzb0PteVkhmjpLaZ/3E/Ao4nBLp9DNVDwQWzZjVdMVQC8WiPkaV6IWD9bc3nDOS8AJfo5NgGZYAJq37hbE811wNcDXJ5Is8ouAt12wWnZxvfvmTksU/FHOA67Vv4QwUSvcNKF0Ktrbsauw9jCmuC/YmB0bnF6I10SN53PuBW9Zz8nZACm2ipqxMQY6HwTacAJcHdIKK4wJPzxgjCIEc5S7CRYosR/i54vYxXOqJkMeP3v0ZygUFT0A24HaFB+KAOYlpEIdZv5CnNtocw3DMkFEEMgAs="
  - secure: "q3lGyhVwwuzkeTC21Tuk22vdHUcjy6373S+6+BJ86dXoXhNKC4t9tG8D+xELO0JNjgyLH9tAVVH/j55zAgKQUnBw2SKYBuMPKnUF3K4RgL8tUmw7rByWJIdoKy+0h2vA4dmGcEhYdN36bG+kVuVrGW33drlLeYgUrwteyjT3svFdkFOQcVaFznHobDlN/+SKvlwF6o71hUUQtBKFAyzSO9DNMS2LvqO54CgyNPnG2pY19ZSbIus+3Xve0EkpOeGZwjLPFJvagigbHigCltQvrVxAgJEMDQffVWxdH07WrG5xlER/xVCf6B56bW1Irk1Wlkd/sW2a9kh0fgtkXtjj9pYZL8+oh4uc3KB1rc0iOSju8kHlJN0141TKiqvzUaWHpBrNtyhWmc80K7uKft2joVKyJZgvaa3hradp1T75JBaBKfubhE6kcdix0w5lNmI0zAr6Clo0Z+IauskZVweDFNEthOsDIrWhan4QhvynEc7w1a+FuSo3eBXsYfrqVmO+2QLRkCYnofK8UEhdPJCnYQqIHcMliG4t09qUMC2a9r5GQiXeqib1aDnRLq4qkbLylbyS0mTsWjcv9lgy7QovEHnX1ygM2RS4mYI9pwAqwDecrPZ/azA9BD9CYqR86zqsdL+BL2/GgMCBcP9PuBiWoJU5cWGVvB1GY4px7w0Fm/A="

notifications:
  webhooks:
    urls:
    - "https://webhooks.gitter.im/e/f7f122123bd58ebb34f5"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - gcc-7
    - g++-7
    - oracle-java8-installer
    - gcc-mingw-w64-base
    - binutils-mingw-w64-x86-64
    - gcc-mingw-w64-x86-64
    - gcc-mingw-w64
    - g++-mingw-w64-x86-64
os:
- linux

before_install:
- sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
- sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
- gcc -v && g++ -v && cmake --version
- export CC=/usr/bin/gcc-7
- export CXX=/usr/bin/g++-7
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then openssl aes-256-cbc -K $encrypted_0b32ef791498_key -iv $encrypted_0b32ef791498_iv -in scripts/travis.enc -out scripts/travis.dec -d; fi
- gpg2 --import scripts/travis.dec

install:
- mvn --settings scripts/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

script:
- mvn package -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true

before_deploy:
- cp scripts/settings.xml $HOME/.m2/settings.xml

after_success:
- "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests --settings scripts/settings.xml"